import type { Metadata } from "next";
import "./globals.css";
import NavLinks from "../components/NavLinks";
import { Poppins } from "next/font/google";
// import HomeAnimatedDivs from "./components/HomeAnimateDivs";
import MouseFollow from "../components/MouseFollow";
import TopBar from "../components/Topbar";
import { ThemeProvider } from "@/components/theme-provider";

const poppins = Poppins({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${poppins.variable} antialiased   font-[family-name:var(--font-poppins)]`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <MouseFollow />
          <main className="container relative mx-auto py-8 md:py-9 h-screen">
            {/* <HomeAnimatedDivs /> */}
            <TopBar />
            {/* <SocialLinks /> */}
            {children}
            <NavLinks />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
